spring.application.name=Salon_Mgmt_Backend

#DB config
spring.datasource.url=jdbc:mysql://localhost:3306/Salon?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=D4_92695_Rushikesh
spring.datasource.password=Rushi@751
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=none

spring.jpa.hibernate.ddl-auto=update
#default server port 8080
server.port=8123
#Spring security properties
#spring.security.user.name=Rama
#spring.security.user.password=123456
#logging.level.org.springframework.security=debug